In [53]:
from pyquaternion import Quaternion as Quat

In [75]:
a = Quat(array=[1,2,3,4])
print(a)

1.000 +2.000i +3.000j +4.000k


In [76]:
a

Quaternion(1.0, 2.0, 3.0, 4.0)

In [77]:
import numpy as np

In [92]:
def func(x):
    x -= x.mean()
    return x




In [93]:
a = np.array([[0., 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
a

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [94]:
func(a)

array([[-4.5, -3.5, -2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5,  3.5,  4.5]])

In [95]:
a

array([[-4.5, -3.5, -2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5,  3.5,  4.5]])